---
title: "Artitst Donut Plots"
author: "Gregory Barber"
date: "April 2, 2019"
output: 
html_document:
  self_contained: no
runtime: shiny
---

<style type="text/css">
.main-container {
  max-width: 1100px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r include = FALSE}
knitr::opts_chunk$set(echo=FALSE, message = FALSE, warning = FALSE)
```

```{r, message = FALSE, warning=FALSE}
#Loaded in Libraries
library(tidyverse)
library(plotly)
library(RColorBrewer)
library(reshape2)
library(viridis)
library(shiny)
```

```{r}

path <- 'https://raw.githubusercontent.com/artofstat/ArtistDiversity/master/artistdata.csv'
artists <- read.csv(path)

```

```{r}

geodf <- artists %>% select(museum, GEO3major) %>% group_by(museum) %>% 
  summarize(Africa=round(100*prop.table(table(GEO3major))[1],1), 
            Asia=round(100*prop.table(table(GEO3major))[2],1), 
            Europe=round(100*prop.table(table(GEO3major))[3],1), 
            "Latin America"=round(100*prop.table(table(GEO3major))[4],1), 
            "North America"=round(100*prop.table(table(GEO3major))[5],1), 
            "West Asia"=round(100*prop.table(table(GEO3major))[6],1)
  )
#geodf

Group <- c(2,3,3,1,3,3,1,4,1,3,4,1,2,1,2,4,5,2)

geodf <- cbind(Group, geodf)

#recode to fit name on plot
levels(geodf$museum)[levels(geodf$museum) == "Metropolitan Museum of Art, New York, NY"]<- "Metropolitan Museum of Art, New York"
#geodf

```

```{r}

art_long <- melt(geodf, id.vars = c("Group","museum"),value.name="Percent", variable.name = "Region") %>%
  arrange(museum)
#head(art_long)

```


```{r}

p <- art_long %>%
  filter(Group == 1)%>%
  arrange(factor(Region, levels =  c("Europe",
                                 "North America",
                                 "Asia",
                                 "Latin America",
                                 "Africa",
                                 "West Asia")))
colors3 <- viridis(6, alpha = .75, begin = 0, end = 1)
M_list <- distinct(p, museum)

plot_vec <- list()
domain_list <- list(list(x = c(1, 2)),list(x = c(-1, -4)),list(x = c(3,6)),list(x = c(0.1, 0.7)),list(x = c(0.9, 1)))

```

```{r}

p <- art_long %>%
  filter(Group == 1)%>%
  arrange(factor(Region, levels =  c("Europe",
                                 "North America",
                                 "Asia",
                                 "Latin America",
                                 "Africa",
                                 "West Asia")))
colors3 <- viridis(6, alpha = .75, begin = 0, end = 1)
M_list <- distinct(p, museum)

plot_vec <- list()

for (i in seq(1,nrow(M_list))){
  x <- filter(p, museum == M_list[i,])
  k <- x %>% plot_ly(sort = FALSE,hovertext = paste("<b>Region:<b>",x$Region,"<br>Percent:",x$Percent,"%"),
                       hoverlabel =list(font = list(size = 12)),
                       labels = ~Region, values = ~Percent, 
                       textinfo = paste(x$Percent), hoverinfo = "text",
                       insidetextfont = list(color = '#FFFFFF'),
                       marker = list(colors=colors3),
                       height = 400
                       ) %>%
  add_pie(hole = 0.6) %>%
  layout(title = '') %>%
  layout(margin = list(t = 80),annotations = list(text = as.character(x$museum),showarrow = FALSE, align = 'right', y = 1.09, font = list(size = 14), yref = "paper"))%>%
  layout(legend = list(x = 0.4,y = 0.5, align = 'right'))
  plot_vec <- append(plot_vec, list(k))
}
```


```{r}
fluidPage(
  column(7,offset = 5,titlePanel("Group 1")),
  fluidRow(
    column(plot_vec[[1]]%>% layout(legend = list(x = 0.29,y = 0.5, align = 'right', bgcolor = 'rgba(0,0,0,0)', font = list(size = 10)))%>% layout(height = 400), width = 4),
    column(plot_vec[[5]]%>% layout(showlegend = FALSE), width = 4),
    column(plot_vec[[3]]%>% layout(showlegend = FALSE), width = 4),
    column(plot_vec[[4]]%>% layout(showlegend = FALSE), width = 4),
    column(plot_vec[[2]]%>% layout(showlegend = FALSE), width = 4)
  )
)
```

```{r}

p <- art_long %>%
  filter(Group == 2)%>%
  arrange(factor(Region, levels =  c("Europe",
                                 "North America",
                                 "Asia",
                                 "Latin America",
                                 "Africa",
                                 "West Asia")))
colors3 <- viridis(6, alpha = .75, begin = 0, end = 1)
M_list <- distinct(p, museum)

plot_vec <- list()

for (i in seq(1,nrow(M_list))){
  x <- filter(p, museum == M_list[i,])
  k <- x %>% plot_ly(sort = FALSE,hovertext = paste("<b>Region:<b>",x$Region,"<br>Percent:",x$Percent,"%"),
                       hoverlabel =list(font = list(size = 12)),
                       labels = ~Region, values = ~Percent, 
                       textinfo = paste(x$Percent), hoverinfo = "text",
                       insidetextfont = list(color = '#FFFFFF'),
                       marker = list(colors=colors3),
                       height = 400
                       ) %>%
  add_pie(hole = 0.6) %>%
  layout(title = '') %>%
  layout(margin = list(t = 80),annotations = list(text = as.character(x$museum),showarrow = FALSE, align = 'right', y = 1.09, font = list(size = 14), yref = "paper"))%>%
  layout(legend = list(x = 0.4,y = 0.5, align = 'right'))
  plot_vec <- append(plot_vec, list(k))
}
```


```{r}
fluidPage(
  column(7,offset = 5,titlePanel("Group 2")),
  fluidRow(
    column(plot_vec[[1]]%>% layout(legend = list(x = 0.29,y = 0.5, align = 'right', bgcolor = 'rgba(0,0,0,0)', font = list(size = 10)))%>% layout(height = 400), width = 4),
    column(plot_vec[[2]]%>% layout(showlegend = FALSE), width = 4),
    column(plot_vec[[3]]%>% layout(showlegend = FALSE), width = 4),
    column(plot_vec[[4]]%>% layout(showlegend = FALSE), width = 4)
  )
)
```

```{r}

p <- art_long %>%
  filter(Group == 3)%>%
  arrange(factor(Region, levels =  c("Europe",
                                 "North America",
                                 "Asia",
                                 "Latin America",
                                 "Africa",
                                 "West Asia")))
colors3 <- viridis(6, alpha = .75, begin = 0, end = 1)
M_list <- distinct(p, museum)

plot_vec <- list()

for (i in seq(1,nrow(M_list))){
  x <- filter(p, museum == M_list[i,])
  k <- x %>% plot_ly(sort = FALSE,hovertext = paste("<b>Region:<b>",x$Region,"<br>Percent:",x$Percent,"%"),
                       hoverlabel =list(font = list(size = 12)),
                       labels = ~Region, values = ~Percent, 
                       textinfo = paste(x$Percent), hoverinfo = "text",
                       insidetextfont = list(color = '#FFFFFF'),
                       marker = list(colors=colors3),
                       height = 400
                       ) %>%
  add_pie(hole = 0.6) %>%
  layout(title = '') %>%
  layout(margin = list(t = 80),annotations = list(text = as.character(x$museum),showarrow = FALSE, align = 'right', y = 1.09, font = list(size = 14), yref = "paper"))%>%
  layout(legend = list(x = 0.4,y = 0.5, align = 'right'))
  plot_vec <- append(plot_vec, list(k))
}
```


```{r}
fluidPage(
  column(7,offset = 5,titlePanel("Group 3")),
  fluidRow(
    column(plot_vec[[1]]%>% layout(legend = list(x = 0.29,y = 0.5, align = 'right', bgcolor = 'rgba(0,0,0,0)', font = list(size = 10)))%>% layout(height = 400), width = 4),
    column(plot_vec[[2]]%>% layout(showlegend = FALSE), width = 4),
    column(plot_vec[[3]]%>% layout(showlegend = FALSE), width = 4),
    column(plot_vec[[4]]%>% layout(showlegend = FALSE), width = 4),
    column(plot_vec[[5]]%>% layout(showlegend = FALSE), width = 4)
  )
)
```

```{r}

p <- art_long %>%
  filter(Group == 3)%>%
  arrange(factor(Region, levels =  c("Europe",
                                 "North America",
                                 "Asia",
                                 "Latin America",
                                 "Africa",
                                 "West Asia")))
colors3 <- viridis(6, alpha = .75, begin = 0, end = 1)
M_list <- distinct(p, museum)

plot_vec <- list()

for (i in seq(1,nrow(M_list))){
  x <- filter(p, museum == M_list[i,])
  k <- x %>% plot_ly(sort = FALSE,hovertext = paste("<b>Region:<b>",x$Region,"<br>Percent:",x$Percent,"%"),
                       hoverlabel =list(font = list(size = 12)),
                       labels = ~Region, values = ~Percent, 
                       textinfo = paste(x$Percent), hoverinfo = "text",
                       insidetextfont = list(color = '#FFFFFF'),
                       marker = list(colors=colors3),
                       height = 400
                       ) %>%
  add_pie(hole = 0.6) %>%
  layout(title = '') %>%
  layout(margin = list(t = 80),annotations = list(text = as.character(x$museum),showarrow = FALSE, align = 'right', y = 1.09, font = list(size = 14), yref = "paper"))%>%
  layout(legend = list(x = 0.4,y = 0.5, align = 'right'))
  plot_vec <- append(plot_vec, list(k))
}
```


```{r}
fluidPage(
  column(7,offset = 5,titlePanel("Group 4")),
  fluidRow(
    column(plot_vec[[1]]%>% layout(legend = list(x = 0.29,y = 0.5, align = 'right', bgcolor = 'rgba(0,0,0,0)', font = list(size = 10)))%>% layout(height = 400), width = 4),
    column(plot_vec[[2]]%>% layout(showlegend = FALSE), width = 4),
    column(plot_vec[[3]]%>% layout(showlegend = FALSE), width = 4)
  )
)
```

```{r}

p <- art_long %>%
  filter(Group == 5)%>%
  arrange(factor(Region, levels =  c("Europe",
                                 "North America",
                                 "Asia",
                                 "Latin America",
                                 "Africa",
                                 "West Asia")))
colors3 <- viridis(6, alpha = .75, begin = 0, end = 1)
M_list <- distinct(p, museum)

plot_vec <- list()

for (i in seq(1,nrow(M_list))){
  x <- filter(p, museum == M_list[i,])
  k <- x %>% plot_ly(sort = FALSE,hovertext = paste("<b>Region:<b>",x$Region,"<br>Percent:",x$Percent,"%"),
                       hoverlabel =list(font = list(size = 12)),
                       labels = ~Region, values = ~Percent, 
                       textinfo = paste(x$Percent), hoverinfo = "text",
                       insidetextfont = list(color = '#FFFFFF'),
                       marker = list(colors=colors3),
                       height = 400
                       ) %>%
  add_pie(hole = 0.6) %>%
  layout(title = '') %>%
  layout(margin = list(t = 80),annotations = list(text = as.character(x$museum),showarrow = FALSE, align = 'right', y = 1.09, font = list(size = 14), yref = "paper"))%>%
  layout(legend = list(x = 0.4,y = 0.5, align = 'right'))
  plot_vec <- append(plot_vec, list(k))
}
```


```{r}
fluidPage(
  column(7,offset = 5,titlePanel("Group 5")),
  fluidRow(
    column(plot_vec[[1]]%>% layout(legend = list(x = 0.29,y = 0.5, align = 'right', bgcolor = 'rgba(0,0,0,0)', font = list(size = 10)))%>% layout(height = 400), width = 4)
  )
)
```







